---
- name: Create Gitea data directory
  file:
    path: /opt/gitea
    state: directory
    mode: '0755'

- name: Create Gitea data directory 
  file:
    path: /opt/gitea/gitea/data
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'  

- name: Create PostgreSQL database for Gitea
  file:
    path: /opt/gitea/postgres/data
    state: directory
    owner: "999"
    group: "999"
    mode: '0700'

- name: Deploy docker-compose.yml for Gitea
  template:
    src: docker-compose.yml.j2
    dest: /opt/gitea/docker-compose.yml
    mode: '0644'

- name: Start Gitea Stack
  community.docker.docker_compose_v2:
    project_src: /opt/gitea
    state: present
    